### ISSUE TITLE
I'm trying to use it locally and it says: Failed to fetch

### ISSUE THREAD

**Issue by xiamuguizhi** [Akohjesse/Vue3-json-server-blog#1]
![](https://vkceyugu.cdn.bspapp.com/VKCEYUGU-2fa930c8-feec-4942-ac88-ba3781377bb0/1446cbc0-eb7c-4f9f-a827-45f2391bc958.jpg)

**Comment by Akohjesse** [comment]
Yes, this is so because I'm using a fake restful api, with <A href="https://github.com/typicode/json-server">Json-server</a> , which watches the data/db.json file. 

To run this, install json-server from npm to the project, then cd into the data folder and run this, 

<code>Json-server --watch db.json</code>

it should work fine then

**Comment by xiamuguizhi** [comment]
@Akohjesse Thanks for your answer, I think I understand.

Thanks again for your answer.
